### PR TITLE
Update entrypoint.sh

### PR DESCRIPTION
**Pull request by sophieqc**
add full path for LD_PRELOAD, It didn't work on docker-ce 18.06.1 and openshift origin 3.9.

### CODE REVIEW

**Comment by jkroepke** [comment]
Hum, okay. Maybe its docker related because we are using 3.9, too.

But why you are change `exec "$@"` to `exec $@` ?

**Comment by sophieqc** [comment]
Did more tests, the change exec "$@" to exec $@ ? is useless, reverting back.

**Comment by jkroepke** [comment]
Thanks!

**Comment by jkroepke** [comment]
@pcurie I have to revert this a litte bit, make it configurable. We are running Openshift on CentOS w/ Docker 1.13 and your Change breaks our environment. So you have to add an environment variable to your configuration now.

See: https://github.com/jkroepke/openshift-mta/pull/3

**Pull request merged**
